---
name: CI

# https://github.com/actions/checkout
# https://github.com/ruby/setup-ruby
# https://github.com/actions/virtual-environments#available-environments
# https://github.com/ruby/setup-ruby/blob/master/README.md#supported-platforms

'on': [push, pull_request, workflow_dispatch]

jobs:
  test:
    name: >-
      ${{ matrix.task }} ${{ matrix.os }} ${{ matrix.ruby }} ${{ matrix.rubyopt }}

    runs-on: ${{ matrix.os }}
    if: |
      !(   contains(github.event.pull_request.title,  '[ci skip]')
        || contains(github.event.pull_request.title,  '[skip ci]'))
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        task:
          - test
        ruby:
          - '3.2'
          - '3.3'
          - '3.4'
          - '4.0'
          - head
        include:
          - os: windows-latest
            ruby: ruby
            task: test
          - os: macos-latest
            ruby: ruby
            task: test
          - os: ubuntu-latest
            ruby: ruby
            task: test
            rubyopt: "--enable-frozen-string-literal"
          - os: ubuntu-latest
            ruby: ruby
            task: "test:isolated"

    steps:
      - name: repo checkout
        uses: actions/checkout@main

      - name: load ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none

      - name: install hoe if not hoe
        run: gem install hoe -N
        if: ${{ github.event.repository.name != 'hoe' }}

      - name: install minitest if not minitest
        run: gem install minitest -N
        if: ${{ github.event.repository.name != 'minitest' }}

      - name: install prism if minitest
        run: gem install prism -N --conservative
        if: ${{ github.event.repository.name == 'minitest' }}

      - name: rake test
        timeout-minutes: 3
        run: |
          rake ${{ matrix.task }} RUBYOPT="${{ matrix.rubyopt }}"
